# Generated by Django 2.1.5 on 2019-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='alias',
            field=models.CharField(default='alias', max_length=50),
            preserve_default=False,
        ),
    ]
